src/Entity/Answers.php
<?php

namespace App\Entity;

use App\Repository\AnswersRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AnswersRepository::class)
 */
class Answers
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $text;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_category;

    /**
     * @ORM\ManyToOne(targetEntity=Personality::class, inversedBy="answers")
     * @ORM\JoinColumn(nullable=false)
     */
    private $personality;

    /**
     * @ORM\ManyToOne(targetEntity=Question::class, inversedBy="answers")
     * @ORM\JoinColumn(nullable=false)
     */
    private $question;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getIdCategory(): ?int
    {
        return $this->id_category;
    }

    public function setIdCategory(int $id_category): self
    {
        $this->id_category = $id_category;

        return $this;
    }

    public function getPersonality(): ?Personality
    {
        return $this->personality;
    }

    public function setPersonality(?Personality $personality): self
    {
        $this->personality = $personality;

        return $this;
    }

    public function getQuestion(): ?Question
    {
        return $this->question;
    }

    public function setQuestion(?Question $question): self
    {
        $this->question = $question;

        return $this;
    }
}

src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 */
class Event
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type_of_event;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_of_event;

    /**
     * @ORM\Column(type="integer")
     */
    private $participants_registered;

    /**
     * @ORM\Column(type="integer")
     */
    private $participants_max;

    /**
     * @ORM\Column(type="integer")
     */
    private $participants_min;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $event_picture;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="event")
     */
    private $users;

    /**
     * @ORM\OneToMany(targetEntity=Comments::class, mappedBy="event")
     */
    private $comments;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $distance;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $niveau;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $estimated_time;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address2;

    /**
     * @ORM\Column(type="integer")
     */
    private $zipcode;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTypeOfEvent(): ?string
    {
        return $this->type_of_event;
    }

    public function setTypeOfEvent(string $type_of_event): self
    {
        $this->type_of_event = $type_of_event;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateOfEvent(): ?\DateTimeInterface
    {
        return $this->date_of_event;
    }

    public function setDateOfEvent(\DateTimeInterface $date_of_event): self
    {
        $this->date_of_event = $date_of_event;

        return $this;
    }

    public function getParticipantsRegistered(): ?int
    {
        return $this->participants_registered;
    }

    public function setParticipantsRegistered(int $participants_registered): self
    {
        $this->participants_registered = $participants_registered;

        return $this;
    }

    public function getParticipantsMax(): ?int
    {
        return $this->participants_max;
    }

    public function setParticipantsMax(int $participants_max): self
    {
        $this->participants_max = $participants_max;

        return $this;
    }

    public function getParticipantsMin(): ?int
    {
        return $this->participants_min;
    }

    public function setParticipantsMin(int $participants_min): self
    {
        $this->participants_min = $participants_min;

        return $this;
    }

    /**
     * isClosed() vérifie si le nombre de participants maximum est atteint
     *
     * @return boolean //true si l'évènement est complet 
     */
    public function isClosed()
    {
      $max= $this->getParticipantsMax();
      $current = $this->getParticipantsRegistered();
      return($max == $current);
    }
    
    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getEventPicture(): ?string
    {
        return $this->event_picture;
    }

    public function setEventPicture(string $event_picture): self
    {
        $this->event_picture = $event_picture;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addEvent($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            $user->removeEvent($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Comments>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setEvent($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getEvent() === $this) {
                $comment->setEvent(null);
            }
        }

        return $this;
    }

    public function getDistance(): ?int
    {
        return $this->distance;
    }

    public function setDistance(?int $distance): self
    {
        $this->distance = $distance;

        return $this;
    }

    public function getNiveau(): ?string
    {
        return $this->niveau;
    }

    public function setNiveau(?string $niveau): self
    {
        $this->niveau = $niveau;

        return $this;
    }

    public function getEstimatedTime(): ?string
    {
        return $this->estimated_time;
    }

    public function setEstimatedTime(?string $estimated_time): self
    {
        $this->estimated_time = $estimated_time;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(?int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getAddress1(): ?string
    {
        return $this->address1;
    }

    public function setAddress1(string $address1): self
    {
        $this->address1 = $address1;

        return $this;
    }

    public function getAddress2(): ?string
    {
        return $this->address2;
    }

    public function setAddress2(?string $address2): self
    {
        $this->address2 = $address2;

        return $this;
    }

    public function getZipcode(): ?int
    {
        return $this->zipcode;
    }

    public function setZipcode(int $zipcode): self
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstname;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birthdate;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $profile_picture;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $phone_number;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $gender;

    /**
     * @ORM\ManyToMany(targetEntity=Event::class, inversedBy="users")
     */
    private $event;

    /**
     * @ORM\OneToMany(targetEntity=Comments::class, mappedBy="user")
     */
    private $comments;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=Personality::class, inversedBy="users")
     */
    private $personality;

    public function __construct()
    {
        $this->event = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getBirthdate(): ?\DateTimeInterface
    {
        return $this->birthdate;
    }

    public function setBirthdate(\DateTimeInterface $birthdate): self
    {
        $this->birthdate = $birthdate;

        return $this;
    }

    public function getProfilePicture(): ?string
    {
        return $this->profile_picture;
    }

    public function setProfilePicture(string $profile_picture): self
    {
        $this->profile_picture = $profile_picture;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPhoneNumber(): ?int
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(int $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    /**
     * @return Collection<int, Event>
     */
    public function getEvent(): Collection
    {
        return $this->event;
    }

    public function addEvent(Event $event): self
    {
        if (!$this->event->contains($event)) {
            $this->event[] = $event;
        }

        return $this;
    }

    public function removeEvent(Event $event): self
    {
        $this->event->removeElement($event);

        return $this;
    }

    /**
     * @return Collection<int, Comments>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPersonality(): ?Personality
    {
        return $this->personality;
    }

    public function setPersonality(?Personality $personality): self
    {
        $this->personality = $personality;

        return $this;
    }
}

templates/profile/index.html.twig
{% extends 'base.html.twig' %}
{% block header %}
	<div class="container-fluid section-top"></div>
{% endblock %}

{% block body %}
	{% block stylesheets %}
		<link rel="stylesheet" href="/assets/css/design-system.css">
		<link rel="stylesheet" href="/assets/css/profil.css">
	{% endblock %}

	{% set age = date("now").diff(date(userData.birthdate)).y %}
	<main class="profile-layout">
		<div class="container-fluid section-top"></div>
		<div class="profil-container d-flex flex-wrap justify-content-center">


			<div class="profil-img-wrapper">
				<img src="/assets/img/{{userData.profilePicture}}" alt="">
			</div>

			<!---------------------- Profil Summary ------------------------>
			{% if personality != null %}
				<div class="section section-container profil-summary-container text-center p-4">
					<div class="profil-summary-top d-flex justify-content-between align-items-center">
						<div class="profil-summary-top-left d-flex align-items-center">
							<a href="">
								<img src="/assets/img/{{ personality.personalityPicture }}" alt="">
							</a>

							<div class="profil-summary-top-left-title-wrapper">
								{% set categories = {1: 'Les Meneurs', 2 : 'Les Éclaireurs', 3 : 'Les Émancipateurs', 4 : 'Les Intermédiaires'}%}
								<h5 class="profil-summary-top-left-title-1 fw-bold">{{ categories[personality.idCategory] }}</h5>
								<div class="profil-summary-top-left-title-2">{{ personality.typeOfPersonality }}</div>
							</div>
						</div>

					</div>
				{% endif %}
				<div class="profil-summary-description-container d-flex flex-wrap justify-content-center text-center text-dark">
					<div class="section profil-summary-description-title mb-0">
						<h4>{{userData.firstname}}
							{{userData.name}}
						</h4>
					</div>
					<div class="profil-summary-description">
						{{userData.description}}
						seule ou en groupe :), je suis nouvelle sur ce site c’est pourquoi je cherche des Amisgo pour
																																																												                        réaliser ma première expérience !
					</div>
				</div>
				<div class="profil-summary-badge-container d-flex justify-content-center">
					<span class="badge  btn-profil p-2">
						{{ age }}
						ans</span>
					<span class="badge btn-profil p-2">{{userData.city}}
					</span>
				</div>
			</div>

			<!---------------------- Liked Events Section -------------------------->
			<div class="section section-container profil-cards-container text-center p-4">
				<div class="profil-cards-title">
					<h4>Evénements likés</h4>
				</div>
				<div class="section profil-cards-wrapper d-flex justify-content-between">
					<div class="profil-card-add d-flex flex-column justify-content-evenly align-items-center">
						<div class="profil-card-add-title">
							Voir plus d'événements
						</div>
						<button class="d-flex justify-content-center align-items-center"><img src="assets/icons/icone-add.svg" alt=""></button>
					</div>
					<div class="profil-card d-flex flex-column justify-content-evenly align-items-center">
						<div class="profil-card-title">
							Tu n'as pas encore liké d'événements
						</div>
					</div>
				</div>
			</div>

			<!---------------------- Recommandations Section -------------------------->
			<div class="section section-container profil-cards-container text-center p-4">
				<div class="row profil-cards-title">
					<h4>Recommandations</h4>
				</div>
				<div class="section profil-cards-wrapper d-flex justify-content-start">
					<div class="profil-card-add d-flex flex-column justify-content-evenly align-items-center">
						<div class="profil-card-add-title">
							Voir plus d'événements
						</div>
						<button class="d-flex justify-content-center align-items-center"><img src="assets/icons/icone-add.svg" alt=""></button>
					</div>
					{% if eventParticipation|length > 0 %}

						<div class="custom-card-item">
							<div class="custom-card-item-top-wrapper">
								<img src="/assets/img/{{eventParticipation[0].eventPicture }}" alt="">

							</div>
							<div class="custom-card-item-bottom d-flex flex-column justify-content-center align-items-center">
								<time>{{eventParticipation[0].dateOfEvent|date("d F y H:m")}}</time>
								<a href="{{ path('app_event_details', {'id': eventParticipation[0].id}) }}">
									<h5>{{eventParticipation[0].title}}</h5>
								</a>
								<p>{{eventParticipation[0].city}}</p>
							</div>
						</div>

					{% endif %}
				</div>
			</div>

			<!---------------------- Participations Section -------------------------->
			<div class="container section section-container profil-cards-container text-center p-4">
				<div class="row profil-cards-title">
					<h4>Participations</h4>
				</div>
				<div class="section profil-cards-wrapper d-flex justify-content-start">
					<div class="profil-card-add d-flex flex-column justify-content-evenly align-items-center">
						<a href="{{ path('app_events') }}">
							<div class="profil-card-add-title">
								Voir plus d'événements
							</div>
						</a>
						<button class="d-flex justify-content-center align-items-center"><img src="assets/icons/icone-add.svg" alt=""></button>
					</div>
					{% if eventParticipation %}
						{% for event in eventParticipation%}
							<div class="custom-card-item">
								<div class="custom-card-item-top-wrapper">
									<img src="/assets/img/{{event.eventPicture }}" alt="">

								</div>
								<div class="custom-card-item-bottom d-flex flex-column justify-content-center align-items-center">
									<time>{{event.dateOfEvent|date("d F y H:m")}}</time>
									<a href="{{ path('app_event_details', {'id': event.id}) }}">
										<h5>{{event.title}}</h5>
									</a>
									<p>{{event.city}}</p>
								</div>
							</div>
						{% endfor %}
					{% endif %}
				</div>
			</div>

			<a href="{{ path('app_persotest') }}">
				<button class="btn btn-heroshot">Refaire le test</button>
			</a>
		</div>
	</main>


{% endblock %}