src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 */
class Event
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type_of_event;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_of_event;

    /**
     * @ORM\Column(type="integer")
     */
    private $participants_registered;

    /**
     * @ORM\Column(type="integer")
     */
    private $participants_max;

    /**
     * @ORM\Column(type="integer")
     */
    private $participants_min;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $event_picture;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="event")
     */
    private $users;

    /**
     * @ORM\OneToMany(targetEntity=Comments::class, mappedBy="event")
     */
    private $comments;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $distance;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $niveau;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $estimated_time;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address2;

    /**
     * @ORM\Column(type="integer")
     */
    private $zipcode;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTypeOfEvent(): ?string
    {
        return $this->type_of_event;
    }

    public function setTypeOfEvent(string $type_of_event): self
    {
        $this->type_of_event = $type_of_event;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateOfEvent(): ?\DateTimeInterface
    {
        return $this->date_of_event;
    }

    public function setDateOfEvent(\DateTimeInterface $date_of_event): self
    {
        $this->date_of_event = $date_of_event;

        return $this;
    }

    public function getParticipantsRegistered(): ?int
    {
        return $this->participants_registered;
    }

    public function setParticipantsRegistered(int $participants_registered): self
    {
        $this->participants_registered = $participants_registered;

        return $this;
    }

    public function getParticipantsMax(): ?int
    {
        return $this->participants_max;
    }

    public function setParticipantsMax(int $participants_max): self
    {
        $this->participants_max = $participants_max;

        return $this;
    }

    public function getParticipantsMin(): ?int
    {
        return $this->participants_min;
    }

    public function setParticipantsMin(int $participants_min): self
    {
        $this->participants_min = $participants_min;

        return $this;
    }

    /**
     * isClosed() vérifie si le nombre de participants maximum est atteint
     *
     * @return boolean //true si l'évènement est complet 
     */
    public function isClosed()
    {
      $max= $this->getParticipantsMax();
      $current = $this->getParticipantsRegistered();
      return($max == $current);
    }
    
    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getEventPicture(): ?string
    {
        return $this->event_picture;
    }

    public function setEventPicture(string $event_picture): self
    {
        $this->event_picture = $event_picture;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addEvent($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            $user->removeEvent($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Comments>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setEvent($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getEvent() === $this) {
                $comment->setEvent(null);
            }
        }

        return $this;
    }

    public function getDistance(): ?int
    {
        return $this->distance;
    }

    public function setDistance(?int $distance): self
    {
        $this->distance = $distance;

        return $this;
    }

    public function getNiveau(): ?string
    {
        return $this->niveau;
    }

    public function setNiveau(?string $niveau): self
    {
        $this->niveau = $niveau;

        return $this;
    }

    public function getEstimatedTime(): ?string
    {
        return $this->estimated_time;
    }

    public function setEstimatedTime(?string $estimated_time): self
    {
        $this->estimated_time = $estimated_time;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(?int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getAddress1(): ?string
    {
        return $this->address1;
    }

    public function setAddress1(string $address1): self
    {
        $this->address1 = $address1;

        return $this;
    }

    public function getAddress2(): ?string
    {
        return $this->address2;
    }

    public function setAddress2(?string $address2): self
    {
        $this->address2 = $address2;

        return $this;
    }

    public function getZipcode(): ?int
    {
        return $this->zipcode;
    }

    public function setZipcode(int $zipcode): self
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }
}

templates/event/activite.html.twig
{% extends 'base.html.twig' %}

{% block title %}Activité{% endblock %}



{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
{% block stylesheets %}
            <link rel="stylesheet" href="/assets/css/design-system.css">
<link rel="stylesheet" href="/assets/css/kayak.css">
	<link rel="stylesheet" href="assets/styles/comments.css"/> 

{# link vers une api pour afficher la map #}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css" integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ==" crossorigin=""/>
{# script lié a une api pour afficher la map #}
<script src="https://unpkg.com/leaflet@1.8.0/dist/leaflet.js" integrity="sha512-BB3hKbKWOc9Ez/TAwyWxNXeoV9c1v6FIeYiBieIWkpLjauysF18NzgR1MBNBXf8/KABdlkX68nAhlwcDFLGPCQ==" crossorigin=""></script>
        {% endblock %}

        <body id="activites">
	<!------------------------ HEADER START------------------------>
	<header>
		<div class="container mw-100 px-0">
			
         <div class="container-fluid section-top-activitee" style="background-image: url({{asset('assets/img/' ~ event.eventPicture)}})">
		 </div>


			<div class="activity-participation-section">
				<div class="activity-summary-container d-flex flex-wrap justify-content-around">
					<div class="activity-back">
						<img class="color" ="/assets/icons/icone-left-arrow.svg" alt="">
					</div>
					<div class="activity-admin d-flex flex-column align-items-center">
						
					<div class="activity-admin-picture">
						<img src="/assets/img/admin-julien.png" alt="">
					</div>
					<h5>Admin</h5>
					</div>
					<div class="activity-summary text-center d-flex flex-column justify-content-center">
						<h4>{{event.typeOfEvent}}</h4>
						<div>
							{{event.description}}
						</div>
					</div>
					<div class="activity-participation d-flex justify-content-around" >
						<button class="icon-btn">
							<img src="/assets/icons/icone-heart-outlined-black.svg" alt="">
						</button>
						{# Si l'evenement est complet  et user n'est pas inscrit#}
						{% if (closed == true and not app.user) or ( (closed == true and app.user) and not participed) %}
							<button> Complet !</button>
						{# Sinon si l'utilisateur est connecté #}
						{% elseif app.user %}
							{# Proposer desinscription ou participation selon ça situation #}               
							<button class="participe" data-rejoins="active" data-id={{ event.id }} 
							{# si l'user est déja inscrit #}
							{% if participed == true %} data-action = "in"
							{% else %} data-action = "out"{% endif %}
							data-new = "">
							</button>
						{# si l'user n'est pas connecté, lui proposer de se connecter #}
						{% else %}
							<a href="{{path("app_login")}}"><p>Connectez-vous pour participer !</p></a>
						{% endif %}
					</div>
				</div>
				{# <div class="activity-summary-more d-flex flex-wrap justify-content-center">
					<div class="activity-summary-more-desc col-4 text-center p-3">
				</div> #}
			</div>
		</div>
	</header>
	<!------------------------ HEADER END------------------------>
	<!------------------------ MAIN START------------------------>
	<main>
		<div class="container text-center 
		d-flex flex-wrap justify-content-center 
		activity-informations-container">
			<div class="activity-information-item">
				<h4>information sur l'activité</h4>
				<p>Adresse : <span>{{event.address1}}</span></p>
				<p>Parcours : <span>Escapade entre aventurier</span></p>
				<p>Distance de parcours : <span>{{event.distance}}</span></p>
				<p>Niveau : <span>{{event.niveau}}</span></p>
				<p>Horaire de départ : <span>10h00</span></p>
				<p>Temps estimé de l'activité : <span>{{event.estimatedTime}}</span></p>

				<div class="activity-information-item-description">
					<p>Tout le matériel vous est fourni</p>
					<div>
						Notre matériel est régulièrement contrôlé. Une partie du stock est renouvelé chaque année pour
						répondre à toutes les normes de sécurité.
					</div>
				</div>

				<div class="activity-information-item-description">
					<p>Que dois-je emporter pour mon activité ?</p>
					<div>
						Le devis imprimé ou le billet électronique reçu lors de votre réservation, pour avoir accès
						gratuitement
						au Parc Floral.
						Pensez à emporter un petit pique-nique pour la pause a midi. Si jamais vous voulez vous
						faciliter la vie, il y a des restaurants disponibles et qui serez ravis de vous accueillir tout
						autour du complexe.
					</div>
				</div>
			</div>
			<div class="activity-information-item d-flex justify-content-center flex-wrap">
				<h4>Informations utiles</h4>
				<div class="activity-information-item-description">
						{{event.description}}

						<br>

						
				</div>

				<div class="activity-information-item-description">
					<p>En cas de mauvais temps</p>
					<div>
						Vous avez réservé un moment d’accrobranche mais le temps n’est pas au rendez-vous ? Nous vous
						proposons un autre rendez-vous.
					</div>
				</div>

				<div class="activity-information-item-description">
					<p>Qui sont-ils?</p>
					<div>
						Moniteurs diplômés d’accrobranche, depuis 2014 l’équipe d’Evasion Verte accueille tout au long
						de l’année des familles et des passionnés de nature et de sport en plein air, venus de toute la
						France et de l’étranger.
					</div>
				</div>

				<div class="activity-price d-flex justify-content-center">
					<div class="title">Tarif : &nbsp;</div>
					<div class="price">&nbsp;{{event.price}}€</div>
				</div>
			</div>

			 <div id="map" class="py-2" style="width:600px; height:400px;"></div>
			 
      <! ----------------- Activity Participants Section ------------------->
		{% if personalities %}
		<div class="activity-participants-container d-flex flex-wrap justify-content-center text-center" style="min-width: 1150px">
			<h4 class="section mb-4">Participants</h4>
			<div class="activity-particpants-wrapper d-flex flex-wrap justify-content-evenly">
			
				{% for perso in personalities %}
					<div class="activity-participant-item d-flex flex-column align-items-center p-3">
						<div class="activity-participant-img">
							<img src="/assets/img/icon-face01.jpg" alt="">
						</div>
					<div class="activity-participant-title mb-4">{{ perso.firstname}} {{ perso.name}}</div>
					<div class="activity-participant-description-wrapper d-flex align-items-center">
						<img src="/assets/img/{{persoImg}}" alt="">
						<div class="activity-particpant-description">{{ persona}}</div>
					</div>
				</div>
			{% endfor %}
				
				<div class="activity-participant-item invitation d-flex flex-column align-items-center p-3">
					<div class="activity-participant-img">
						<img src="/assets/icons/icone-user.svg" alt="">
					</div>
					<div class="activity-participant-title mb-4">Inviter un Amisgo</div>
					<div class="activity-participant-description-wrapper d-flex align-items-center">
						<button class="d-flex justify-content-center align-items-center">
							<img src="/assets/icons/icone-add.svg" alt="">
						</button>
					</div>
				</div>
			</div>
			<div class="activity-participation d-flex justify-content-around p-3" >
			{% if (closed == true and not app.user) or ( (closed == true and app.user) and not participed) %}
				<button> Complet !</button>
			{% elseif app.user %}
				<button class="participe" data-rejoins = "active"></button>
			</div>
			{%  endif %}
		</div>
		{% endif %}
     
	
</div>

	</div>
    
 
    {% if app.user and participed %}
	<div class="activity-chat-container d-flex flex-wrap justify-content-center">
		<div class="activity-chat-title section text-center mb-3">
			<h4>Conversation de groupe</h4>
		</div>
		<div class="container-chat">
			<div class="chat-conversation-container">
				<div class="chat-conversation-wrapper d-flex justify-content-center align-items-end mb-5">
					
						<div class="container w-75" id="root" 
						{% if app.user %} 
						data-user = {{app.user.id}} 
						{% else %} 
						data-user = "" 
						{% endif %}>
					
				</div>
			</div>	
		</div>
	</div>
	{% endif %}

	</main>
    {% endblock %}

 
{% block javascripts %}
		 
	<script src="/javascript/map.js"></script>
	<script src="/javascript/event.js"></script>


	{{ encore_entry_script_tags('comments') }}
  <script>
    //recuperation des champs liés a l'adresse d'un evenement dans notre base de données
    addMarkerFromAdress('{{event.address1}} {{event.zipcode}} {{event.city}}');
  </script>
 
{% endblock %}

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Activités
{% endblock %}
{% block stylesheets %}
	<link rel="stylesheet" href="assets/css/design-system.css">
	<link rel="stylesheet" href="assets/css/activites.css">
{% endblock %}
{% block body %}
	<style>
		.example-wrapper {
			margin: 1em auto;
			max-width: 800px;
			width: 95%;
			font: 18px / 1.5 sans-serif;
		}
		.example-wrapper code {
			background: #F5F5F5;
			padding: 2px 6px;
		}
	</style>
	<div class="container-fluid section-top activite-pict mb-5">
		<div class="row">
			<div class="col-12 col-xl-8">
				<h1>Apprendre le langage des Fleurs</h1>
				<p class="">
					Dîtes-le avec des fleurs ! Chez ARUM, venez et apprenez à réaliser un bouquet de fleurs ou une composition florale selon vos envies, votre créativité et votre personnalité.
				</p>
				<div class="d-flex justify-content-end me-5" id="decouvrir">
					<button type="button" class="btn btn-heroshot">
						<a href="#">Découvrir</a>
					</button>
				</div>
			</div>
		</div>
	</div>
	<!--------------------- IMPORTANT METTRE le div root à l'endroit où l'on souhaite qu'il soit affiché sur la page -------------------->
	<div class="container w-75" id="root"></div>


	<!-- Filter Button Section -->

	<div class="d-flex flex-wrap justify-content-around section" id="filter-button-wrapper">
		<div class="row">
		{% for key, box in filtre %}
			<div class="col-3">
			<button id="{{key}}" class="filter-button btn-filter d-flex btn btn-warning align-items-center p-2 m-auto mt-3 mb-3">
				<div class="icon-background">
					<img src="assets/icons/icone-{{ key }}.svg" alt="">
				</div>
				<div class="activity-title">{{box }}</div>
			</button>
		</div>
		{% endfor %}
		</div>
	</div>
	<!--------------------- Recommandations Section -------------------->
	<div class="section container-fluid section-cards-container">
		<h3 class="cards-title">Recommandés pour vous</h3>
		<h3>{{ messageUser }}</h3>
		{% if app.user %}
		<div class="section cards-container d-flex flex-wrap justify-content-center">
			{% set i = 0 %}
			{% for suggestedEvent in suggestedEvents %}
				{% set display = 'block' %}
				{% if i > 3 %}
					{% set display = 'none' %}
				{% endif %}
				<article class="{% if i > 3 %} suggested {% endif %}col-6 card-item d-flex flex-row" data-category="{{suggestedEvent.category}}" style="display:{{display}}">
					<div class="card-item-img-wrapper">
						<div class="card-item-like-icon">
							<button><img src="assets/icons/icone-heart.svg" alt=""></button>
						</div>
						<img class="card-item-img" src="assets/img/{{ suggestedEvent.eventPicture }}" alt="">
					</div>

					<div class="d-flex flex-column card-item-body">
						<time class="d-flex justify-content-end" datetime="2018-07-03T20:00:00">{{ suggestedEvent.dateOfEvent|date("d F y H:m")}}</time>
						<div class="card-item-body-container">
							
							{# AJOUT D'UN LIEN DYNAMIQUE VERS UNE PAGE ACTIVITE EN PARTICULIER EN RECUPERANT L'ID POUR LE RAJOUTER DYNAMIQUEMENT AU PATH #} 
							<a href="{{ path('app_event_details', {'id': suggestedEvent.id}) }}"><h4 class="text-start">{{ suggestedEvent.title }}</h4></a>
							<h5 class="text-start">{{ suggestedEvent.city }}</h5>
							<p class="text-start1 lh-1 p-3">{{ suggestedEvent.description }}</p>
							<div class="d-flex flex-row justify-content-between">
								<div class="filtre">
									<button class="d-flex btn card-filter-btn btn-warning align-items-center justify-content-start p-0">
										<div class="icon-background">
											<img src="assets/icons/icone-pleinair.svg" alt="">
										</div>
										<div class="card-activity-title mx-2">{{ suggestedEvent.typeOfEvent}}</div>
									</button>
								</div>

								<div class="d-flex justify-content-end iconeparticipants align-items-center">
									<div class="icon-wrapper icons-position icon-position-1"><img class="icon-participants" src="assets/icons/icone-user.svg"></div>
									<div class="icon-wrapper icons-position icon-position-2"><img class="icon-participants" src="assets/icons/icone-user.svg"></div>
									<div class="icon-wrapper icons-position icon-position-3"><img class="icon-participants" src="assets/icons/icone-user.svg"></div>
									<div class="icon-wrapper icons-position icon-position-4"><img class="icon-participants" src="assets/icons/icone-user.svg"></div>
									<div class="icon-wrapper icons-position icon-position-5"><img class="icon-participants" src="assets/icons/icone-user.svg"></div>
									<div class="icon-wrapper icons-position icon-position-6">{{ suggestedEvent.participantsRegistered}}/{{ suggestedEvent.participantsMax }}</div>
								</div>
							</div>
						</div>
					</div>
				</article>
				

				{% set i = i + 1 %}
			{% endfor %}
		{% endif %}
		</div>
		
			{% if suggestedEvents|length > 3 %}
			<button class="see-more-btn" data-action ='' data-id="0">En voir plus</button>
			{% endif %}
	</div>

	<!--------------------- Popular Section -------------------->
	<div class="section container-fluid section-cards-container">
		<h3 class="cards-title">Les plus populaires</h3>
		<h3>{{ message }}</h3>
		<div class="section  cards-container  d-flex flex-wrap justify-content-center">
			{% set i = 0 %}
			{% for popularEvent in popularEvents %}
				{% set display = 'block' %}
				{% if i > 3 %}
					{% set display = 'none !important' %}
				{% endif %}
				<article class="{% if i > 3 %} popular {% endif %}col-6 card-item d-flex flex-row" data-category="{{popularEvent.category}}" style="display:{{display}}">
					<div class="card-item-img-wrapper">
						<div class="card-item-like-icon">
							<button><img src="assets/icons/icone-heart.svg" alt=""></button>
						</div>
						<img class="card-item-img" src="assets/img/{{ popularEvent.eventPicture }}" alt="">
					</div>

					<div class="d-flex flex-column card-item-body">
						<time class="d-flex justify-content-end" datetime="2018-07-03T20:00:00">{{ popularEvent.dateOfEvent|date("d F y H:m")}}</time>
						<div class="card-item-body-container">

							{# AJOUT D'UN LIEN DYNAMIQUE VERS UNE PAGE ACTIVITE EN PARTICULIER EN RECUPERANT L'ID POUR LE RAJOUTER DYNAMIQUEMENT AU PATH #} 
							<a href="{{ path('app_event_details', {'id': popularEvent.id}) }}"><h4 class="text-start">{{ popularEvent.title }}</h4></a>
							<h5 class="text-start">{{ popularEvent.city }}</h5>
							<p class="text-start1 lh-1 p-3">{{ popularEvent.description }}</p>

							<div class="d-flex flex-row justify-content-between">
								<div class="filtre">
									<button class="d-flex btn card-filter-btn btn-warning align-items-center justify-content-start p-0">
										<div class="icon-background">
											<img src="assets/icons/mountains_88302.svg" alt="">
										</div>
										<div class="card-activity-title mx-2">{{ popularEvent.typeOfEvent }}</div>
									</button>
								</div>

								<div class="d-flex justify-content-end iconeparticipants align-items-center">
									<div class="icon-wrapper icons-position icon-position-1"><img class="icon-participants" src="assets/icons/icone-user.svg"></div>
									<div class="icon-wrapper icons-position icon-position-2"><img class="icon-participants" src="assets/icons/icone-user.svg"></div>
									<div class="icon-wrapper icons-position icon-position-3"><img class="icon-participants" src="assets/icons/icone-user.svg"></div>
									<div class="icon-wrapper icons-position icon-position-4"><img class="icon-participants" src="assets/icons/icone-user.svg"></div>
									<div class="icon-wrapper icons-position icon-position-5"><img class="icon-participants" src="assets/icons/icone-user.svg"></div>
									<div class="icon-wrapper icons-position icon-position-6">{{ popularEvent.participantsRegistered}}/{{ popularEvent.participantsMax }}</div>
								</div>
							</div>
						</div>
					</div>
				</article>

				{% set i = i + 1 %}
			{% endfor %}

		</div>
		{% if popularEvents|length > 3 %}
		<button class="see-more-btn" data-action ='' data-id="1">En voir plus</button>
		{% endif %}
	</div>


	<!--------------------- Coming soon Section -------------------->
	<div class="section container-fluid section-cards-container">
		<h3 class="cards-title">A venir</h3>
		<h3>{{ message }}</h3>
		<div class="section cards-container d-flex flex-wrap justify-content-center">
			{% set i = 0 %}
			{% for futureEvent in futureEvents %}
				{% set display = 'block' %}
				{% if i > 3 %}
					{% set display = 'none !important' %}
				{% endif %}
				<article class="{% if i > 3 %} future {% endif %} col-6 card-item d-flex flex-row" data-category="{{futureEvent.category}}" style="display:{{display}}">
					<div class="card-item-img-wrapper">
						<div class="card-item-like-icon">
							<button><img src="assets/icons/icone-heart.svg" alt=""></button>
						</div>
						<img class="card-item-img" src="assets/img/{{ futureEvent.eventPicture }}" alt="">
					</div>

					<div class="d-flex flex-column card-item-body">
						<time class="d-flex justify-content-end" datetime="2018-07-03T20:00:00">{{futureEvent.dateOfEvent|date("d F y H:m")}}</time>
						<div class="card-item-body-container">
							{# AJOUT D'UN LIEN DYNAMIQUE VERS UNE PAGE ACTIVITE EN PARTICULIER EN RECUPERANT L'ID POUR LE RAJOUTER DYNAMIQUEMENT AU PATH #} 
							<a href="{{ path('app_event_details', {'id': futureEvent.id}) }}"><h4 class="text-start">{{ futureEvent.title }}</h4></a>
							<h5 class="text-start">{{ futureEvent.city }}</h5>
							<p class="text-start1 lh-1 p-3">{{ futureEvent.description }}</p>

							<div class="d-flex flex-row justify-content-between">
								<div class="filtre">
									<button class="d-flex btn card-filter-btn btn-warning align-items-center justify-content-start p-0">
										<div class="icon-background">
											<img src="assets/icons/icone-{{ futureEvent.category }}.svg" alt="">
										</div>
										<div class="card-activity-title mx-2">{{ futureEvent.typeOfEvent }}</div>
									</button>
								</div>

								<div class="d-flex justify-content-end iconeparticipants align-items-center">
									<div class="icon-wrapper icons-position icon-position-1"><img class="icon-participants" src="assets/icons/icone-user.svg"></div>
									<div class="icon-wrapper icons-position icon-position-2"><img class="icon-participants" src="assets/icons/icone-user.svg"></div>
									<div class="icon-wrapper icons-position icon-position-3"><img class="icon-participants" src="assets/icons/icone-user.svg"></div>
									<div class="icon-wrapper icons-position icon-position-4"><img class="icon-participants" src="assets/icons/icone-user.svg"></div>
									<div class="icon-wrapper icons-position icon-position-5"><img class="icon-participants" src="assets/icons/icone-user.svg"></div>
									<div class="icon-wrapper icons-position icon-position-6">{{ futureEvent.participantsRegistered}}/{{ futureEvent.participantsMax }}</div>
								</div>
							</div>
						</div>
					</div>
				</article>
				{% set i = i + 1 %}
			{% endfor %}
			{% if futureEvents|length > 3 %}
		</div>
		<button class="see-more-btn" data-action ='' data-id="2">En voir plus</button>
	</div>
	{% endif %}
{% endblock %}

{% block javascripts %}
	{{ encore_entry_script_tags('app') }}
	<script src="/javascript/filtre.js"></script>
{% endblock %}