src/Entity/Answers.php
<?php

namespace App\Entity;

use App\Repository\AnswersRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AnswersRepository::class)
 */
class Answers
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $text;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_category;

    /**
     * @ORM\ManyToOne(targetEntity=Personality::class, inversedBy="answers")
     * @ORM\JoinColumn(nullable=false)
     */
    private $personality;

    /**
     * @ORM\ManyToOne(targetEntity=Question::class, inversedBy="answers")
     * @ORM\JoinColumn(nullable=false)
     */
    private $question;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getIdCategory(): ?int
    {
        return $this->id_category;
    }

    public function setIdCategory(int $id_category): self
    {
        $this->id_category = $id_category;

        return $this;
    }

    public function getPersonality(): ?Personality
    {
        return $this->personality;
    }

    public function setPersonality(?Personality $personality): self
    {
        $this->personality = $personality;

        return $this;
    }

    public function getQuestion(): ?Question
    {
        return $this->question;
    }

    public function setQuestion(?Question $question): self
    {
        $this->question = $question;

        return $this;
    }
}

src/Entity/Personality.php
<?php

namespace App\Entity;

use App\Repository\PersonalityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PersonalityRepository::class)
 */
class Personality
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type_of_personality;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $personality_picture;

    /**
     * @ORM\OneToMany(targetEntity=Answers::class, mappedBy="personality")
     */
    private $answers;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $descrip2_title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $descrip2_text;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $quality_1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $quality_2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $quality_3;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $quote;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $descrip3_title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $descrip3_text;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $personality_picture_2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $slogan;

    /**
     * @ORM\OneToMany(targetEntity=User::class, mappedBy="personality")
     */
    private $users;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_category;

    public function __construct()
    {
        $this->answers = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTypeOfPersonality(): ?string
    {
        return $this->type_of_personality;
    }

    public function setTypeOfPersonality(string $type_of_personality): self
    {
        $this->type_of_personality = $type_of_personality;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPersonalityPicture(): ?string
    {
        return $this->personality_picture;
    }

    public function setPersonalityPicture(string $personality_picture): self
    {
        $this->personality_picture = $personality_picture;

        return $this;
    }

    /**
     * @return Collection<int, Answers>
     */
    public function getAnswers(): Collection
    {
        return $this->answers;
    }

    public function addAnswer(Answers $answer): self
    {
        if (!$this->answers->contains($answer)) {
            $this->answers[] = $answer;
            $answer->setPersonality($this);
        }

        return $this;
    }

    public function removeAnswer(Answers $answer): self
    {
        if ($this->answers->removeElement($answer)) {
            // set the owning side to null (unless already changed)
            if ($answer->getPersonality() === $this) {
                $answer->setPersonality(null);
            }
        }

        return $this;
    }

    public function getDescrip2Title(): ?string
    {
        return $this->descrip2_title;
    }

    public function setDescrip2Title(?string $descrip2_title): self
    {
        $this->descrip2_title = $descrip2_title;

        return $this;
    }

    public function getDescrip2Text(): ?string
    {
        return $this->descrip2_text;
    }

    public function setDescrip2Text(?string $descrip2_text): self
    {
        $this->descrip2_text = $descrip2_text;

        return $this;
    }

    public function getQuality1(): ?string
    {
        return $this->quality_1;
    }

    public function setQuality1(?string $quality_1): self
    {
        $this->quality_1 = $quality_1;

        return $this;
    }

    public function getQuality2(): ?string
    {
        return $this->quality_2;
    }

    public function setQuality2(?string $quality_2): self
    {
        $this->quality_2 = $quality_2;

        return $this;
    }

    public function getQuality3(): ?string
    {
        return $this->quality_3;
    }

    public function setQuality3(?string $quality_3): self
    {
        $this->quality_3 = $quality_3;

        return $this;
    }

    public function getQuote(): ?string
    {
        return $this->quote;
    }

    public function setQuote(?string $quote): self
    {
        $this->quote = $quote;

        return $this;
    }

    public function getDescrip3Title(): ?string
    {
        return $this->descrip3_title;
    }

    public function setDescrip3Title(?string $descrip3_title): self
    {
        $this->descrip3_title = $descrip3_title;

        return $this;
    }

    public function getDescrip3Text(): ?string
    {
        return $this->descrip3_text;
    }

    public function setDescrip3Text(?string $descrip3_text): self
    {
        $this->descrip3_text = $descrip3_text;

        return $this;
    }

    public function getPersonalityPicture2(): ?string
    {
        return $this->personality_picture_2;
    }

    public function setPersonalityPicture2(?string $personality_picture_2): self
    {
        $this->personality_picture_2 = $personality_picture_2;

        return $this;
    }

    public function getSlogan(): ?string
    {
        return $this->slogan;
    }

    public function setSlogan(?string $slogan): self
    {
        $this->slogan = $slogan;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->setPersonality($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getPersonality() === $this) {
                $user->setPersonality(null);
            }
        }

        return $this;
    }

    public function getIdCategory(): ?int
    {
        return $this->id_category;
    }

    public function setIdCategory(int $id_category): self
    {
        $this->id_category = $id_category;

        return $this;
    }
}

src/Controller/PersotestController.php
<?php

namespace App\Controller;


use App\Repository\PersonalityRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\QuestionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;


class PersotestController extends AbstractController
{
    /**
     * @Route("/persotest", name="app_persotest")
     */
    public function index(QuestionRepository $questionRepository): Response
    {
        //permet d'afficher la première série de questions. Il s'agit de la série 0.
        $firstSetOfQuestions = $questionRepository->findBy(['question_set' => 0]);

        return $this->render(
            'persotest/index.html.twig',
            ['questions' => $firstSetOfQuestions]
        );
    }

    /**
     * @Route("/persotest/page2", name="app_persotest2")
     */
    public function getSecondSetOfQuestions(Request $request, QuestionRepository $questionRepository)
    {
        // dd($request);

        $tabCategory = [];
        // on récupère la série de question 0 grâce à la méthode findBy().
        $firstSetOfQuestions = $questionRepository->findBy(['question_set' => 0]);
        //on créé une boucle qui va récupérer pour chaque réponses de l'utilisateur, la catégorie à laquelle elles appartiennent.
        foreach ($firstSetOfQuestions as $row) {
            //on récupére la valeur du "name" dans le formulaire page 1 "flexRadioDefault" avec l'id concaténné des réponses selectionnées
            $param = $request->get('flexRadioDefault' . $row->getId());
            // l'id_category correspond aux catégories de personnalités (il y en a 4 qui contiennent chacune 3 personnalités)
            // on vérifie si la catégorie est déjà présente dans le tableau $tab. Si ça n'est pas le cas on l'ajoute
            if (!isset($tabCategory[$param])) {
                $tabCategory[$param] = 1;
            } else {
                $tabCategory[$param] = $tabCategory[$param] + 1;
            }
        }

        //trie le tableau en ordre décroissant ce qui permet d'avoir en premier élement du tableau, la catégorie avec le plus grand nombre de réponses
        arsort($tabCategory);

        //sachant que la première valeur du tableau est la plus grande on fait une boucle pour vérifier si les valeurs suivantes sont identiques à la première valeur
        $equaltab = [];
        $max = 0;
        foreach ($tabCategory as $key => $value) {
            if ($max == 0) {
                $max = $value;
            }
            if ($value == $max) {
                $equaltab[] = $key;
            }
        }

        // on fait un "random" pour trouver un index aléatoire qui ne dépasse pas la longueur du tableau contenant les catégories avec des égalités.
        $indexCat = random_int(0, count($equaltab) - 1);

        $cat = $equaltab[$indexCat];
        $secondSetOfQuestions = $questionRepository->findBy(['question_set' => $cat]);


        return $this->render(
            'persotest/index_page2.html.twig',
            ['questions' => $secondSetOfQuestions, 'cat' => $cat]
        );
    }



    /**
     * @Route("/persotest/result", name="app_result")
     */
    public function getTestResult(Request $request, QuestionRepository $questionRepository, PersonalityRepository $personalityRepository, EntityManagerInterface $entityManager)
    {
        $tabPerso = [];
        //on récupère la catégorie dans la 2ème page twig du formulaire via un champs caché "<input type="hidden" name="serie" value="{{ cat }}">".
        $cat = $request->get('serie');
        //la série de question correspond à la catégorie de personnalité 
        $secondSetOfQuestions = $questionRepository->findBy(['question_set' => $cat]);

        // le foreach permet de parcourir le tableau de personnalités des réponses de l'utilisateur ($tabPerso)
        foreach ($secondSetOfQuestions as $row) {
            // on récupère les id de personnalité des réponses
            $param = $request->get('flexRadioDefault' . $row->getId());
            // on vérifie si la personnalité est déjà présente dans le tableau $tabPerso. Si ça n'est pas le cas on l'ajoute
            if (!isset($tabPerso[$param])) {
                $tabPerso[$param] = 1;
            } else {
                $tabPerso[$param] = $tabPerso[$param] + 1;
            }
        }
        //trie le tableau en ordre décroissant ce qui permet d'avoir en premier élement du tableau, l'id personnalité avec le plus grand nombre de réponses
        arsort($tabPerso);


        //sachant que la première valeur du tableau est la plus grande on fait une boucle pour vérifier si les valeurs suivantes sont identiques à la première valeur
        $equaltab = [];
        $max = 0;
        foreach ($tabPerso as $key => $value) {
            if ($max == 0) {
                $max = $value;
            }
            if ($value == $max) {
                $equaltab[] = $key;
            }
        }
        //on fait un random quelque soit la taille du tableau de personnalité car s'il n'y a qu'une seule id personnalité dans le tableau le resultat sera forcément l'index de l'id 
        //le random permet également d'obtenir un id aléatoire entre les id avec égalité présentes dans le tableau
        $indexPerso = random_int(0, count($equaltab) - 1);


        $perso = $equaltab[$indexPerso];

        $result = $personalityRepository->findOneById($perso);

        $user = $this->getUser();
        $user->setPersonality($result);


        $entityManager->persist($user);
        $entityManager->flush();

        return $this->render(
            'persotest/index_page_result.html.twig',
            [
                'personality' => $result,
            ]
        );
    }
}

templates/persotest/index.html.twig
{% extends "base.html.twig" %}

{% block header %}{% endblock %}
{% block stylesheets %}
	<link rel="stylesheet" href="/assets/css/questionnaire.css">
{% endblock %}
{% block body %}
	<body id="test01">
		<main>
			<div class="container_quiz">
				<div class="row">
					<div class="col-5 signup-section quiz-section">
						<div class="page-number d-flex justify-content-end">
							<p class="page-counter">1 sur 2</p>
						</div>
						<!--Title -->
						<div class="text-center">
							<h3>Quel amisgo es-tu ?</h3>
						</div><br/>
						<!--Form section-->
						<form
							action="/persotest/page2" method="post">
							<!--Question section-->
							<div
								class="">
								<!--boucle question-->
								{% for question in questions %}

									<label for="">
										<h5 class="question-title">{{question.text}}</h5>
									</label><br/>

									<!--boucle réponse-->
									{% for answer in question.answers %}
										<div class="form-check">
											<input class="form-check-input" required type="radio" name="flexRadioDefault{{ question.id }}" id="flexRadioDefault1" value="{{answer.idCategory}}">
											<label class="form-check-label" for="flexRadioDefault1">
												{{answer.text}}
											</label>
										</div>
									{% endfor %}
								{% endfor %}
							</div><br/>
							<!--Send section-->
							<div class="text-center">
							
								<input type="submit" value="Suivant" class="btn btn-heroshot">
							</div>
						</form>
					</div>
				</div>
			</div>
		</main>
	</body>
{% endblock %}

templates/persotest/index_page2.html.twig
{% extends "base.html.twig" %}

{% block header %}{% endblock %}


{% block body %}
	{% block stylesheets %}
		<link rel="stylesheet" href="/assets/css/design-system.css">
		<link rel="stylesheet" href="/assets/css/questionnaire.css">
	{% endblock %}

	<body id="test02">
		<main>
			<div class="container ">
				<div class="row">
					<div class="col-5 signup-section quiz-section">
						<div class="page-number d-flex justify-content-end">
							<p class="page-counter">2 sur 2</p>
						</div>
						<div class="text-center">
							<h3>Quel amisgo es-tu ?</h3>
						</div><br/>
						<!--Form section-->
						<form action="/persotest/result" method="post">
							<!--on ajoute un champs caché à l'affichage de la page ("hidden") pour récupérer la valeur de la catégorie de personnalité-->
							<!-- les numéros de catégories de personnalité équivalent aux numéros de séries de questions. -->
							<input
							type="hidden" name="serie" value="{{ cat }}"> <!--Question section-->
							<div
								class="">
								<!--boucle question-->
								{% for question in questions %}

									<label for="">
										<h5 class="question-title">{{question.text}}</h5>
									</label><br/>

									<!--boucle réponse-->
									{% for answer in question.answers %}
										<div class="form-check">
											<input class="form-check-input" required type="radio" name="flexRadioDefault{{ question.id }}" id="flexRadioDefault1" value="{{answer.personality.id}}">
											<label class="form-check-label" for="flexRadioDefault1">
												{{answer.text}}
											</label>
										</div>
									{% endfor %}
								{% endfor %}
							</div><br/>
							<!--Send section-->
							<div class="text-center">
								<input type="submit" value="Résultat" class="btn btn-heroshot">
							</div>
						</form>
					</div>
				</div>
			</div>
		</main>
	</body>
{% endblock %}

templates/persotest/index_page_result.html.twig
{% extends "base.html.twig" %}

{% block header %}{% endblock %}
{% block body %}
	{% block stylesheets %}
		<link rel="stylesheet" href="/assets/css/resultats.css">
	{% endblock %}

	<main
		id="resultats">
		<!-- personnalité résultats card section -->
		<section class="container-fluid">
			<article class="row resultats-card">
				<div class="col-5 resultats-img">
					<img src="/assets/img/{{personality.personalityPicture}}" alt="">
				</div>

				<div class="col-7 text-center d-flex flex-column justify-content-center align-items-center resultats-txt ">
					<h3>Tu es :</h3>
					<h2>{{personality.typeOfPersonality}}</h2>
					<p>{{personality.typeOfPersonality}}
						appartient à la famille : Éclaireurs</p>
				</div>
			</article>
		</section>

		<!-- divider section -->
		<div class="container-fluid">
			<div class="row g-0 divider-section">
				<img class="col-12" src="/assets/img/Separateur-courbe.png" alt="séparateur vague">
			</div>
		</div>

		<!-- description section -->
		<section class="container-fluid">
			<div class="row description-section">
				<div class="col-6">
					<p>
						{{personality.description}}
					</p>
				</div>
			</div>
		</section>

		<!-- points forts section -->
		<section class="container-fluid">
			<div class="row points-forts-container">
				<div class="col-7"></div>
				<div class="col-5 points-forts-list">
					<h4>Tes points forts</h4>
					<ul>
						<li>{{personality.quality1}}</li>
						<li>{{personality.quality2}}</li>
						<li>{{personality.quality3}}</li>
					</ul>
				</div>
			</div>
		</section>

		<!-- artiste section -->
		<section class="container-fluid">
			<div class="row artist-section">
				<article class="col-7 artist-txt">
					<h4 class="text-center">{{personality.descrip2Title}}</h4>
					<p>
						{{personality.descrip2Text}}
					</p>
				</article>
			</div>
		</section>

		<!-- quote section -->
		<section class="container-fluid quote-section-container">
			<div class="row quote-section text-center">
				<article class="col">
					<q>
						{{personality.quote}}</q>
				</article>
			</div>
		</section>

		<!-- Sociable section -->
		<section class="container-fluid">
			<div class="row sociable-section">
				<div class="col-6">
					<img src="/assets/img/img-sociable.png" alt="">

				</div>
				<article class="col-6 sociable-txt">
					<h4>
						{{personality.descrip3Title}}</h4>
					<p>{{personality.descrip3Text}}
					</p>
				</article>
			</div>
		</section>

		<!-- match section -->
		<section class="container-fluid match-section-container">
			<div class="row match-section">
				<div class="col-6 text-center">
					<h4>{{personality.typeOfPersonality}} match avec :</h4>
				</div>
			</div>

			<div class="row">
				<article class="col-6 d-flex flex-wrap justify-content-center">
					<div class="card card-match">
						<img src="/assets/img/Ellipse-createur.png" class="card-img-top" alt="...">
						<div class="card-body">
							<h5 class="card-text">Les Créateurs</h5>
						</div>
					</div>

					<div class="card card-match">
						<img src="/assets/img/Ellipse-populaire.png" class="card-img-top" alt="...">
						<div class="card-body">
							<h5 class="card-text">Les Populaires</h5>
						</div>
					</div>

					<div class="card card-match">
						<img src="/assets/img/Ellipse-heros.png" class="card-img-top" alt="...">
						<div class="card-body">
							<h5 class="card-text">Les Héros</h5>
						</div>
					</div>
				</article>

				<div class="col-6 text-end">
					<img src="/assets/img/img-match.png" alt="">
				</div>

			</div>
		</section>

		<!-- call to action section -->
		<section class="container-fluid">
			<div class="row calltoaction-section">
				<h3 class="col-12 text-center calltoaction-txt">
					{{personality.slogan}}
				</h3>

				<div class="col-12 text-center ">
					
						<a href="{{ path('app_events') }}">
							<button class="see-more-btn  btn btn-heroshot">
								C'est parti !
							</button>
						</a>

				</div>
			</div>
		</section>
	</main>
{% endblock %}